services:
  - type: worker
    name: orange-carrier-bot
    runtime: python
    pythonVersion: "3.11"
    
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ORANGE_EMAIL
        sync: false
      - key: ORANGE_PASSWORD
        sync: false
      - key: CHAT_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: POLL_INTERVAL
        value: "10"
      - key: CDR_API_TEMPLATE
        value: "https://www.orangecarrier.com/CDR/mycdrs?start=0&length=50"
